markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            一个博客
tagline:          '今天仍然没有练琴。我当初说什么来着-_-b'
baseurl:          /

author:
  name:           nobody

paginate:         5
recent-num:       5
article_num:      5
